config/routes.rb
SRA::Application.routes.draw do

  devise_for :users ,:path => '', :path_names => {:sign_in => "", :sign_out => ""}

  resources :atendimentos do

     get :autocomplete_user_name, :on => :collection
  end

  resources :professors
 
  resources :types do
    get 'type_by_place', :on => :collection
  end
  resources :places
    resources :servidors

  root :to => 'application#index'

end

app/views/shared/_flash_messages.html.erb
<script type="text/javascript">
    window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove();
        });
    }, 3000);
</script>
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top navbar-inverse" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="">
        <img src="/assets/UnB3.png">
      </a>

      <div class = "logged" align='right'>
        <%  if user_signed_in? %>


            <button type="button" class="btn btn-info navbar-btn"><i class="fa fa-gear"></i>
              <%=  current_user.name%></button>
            <%=link_to raw("<i class=\"fa fa-sign-out\"> Sair </i>"),
                       destroy_user_session_path,
                       class: "btn  btn-danger navbar-btn", :id => 'logout', method: "delete", confirm: "Deseja realmente sair?" %>


        <% end %>
      </div>

    </div><!--/.nav-collapse -->
  </div>

</div>
</div>

app/views/shared/_navbar_collapsible.html.erb
<div class="list-group" role="navigation">
  <div class="container-nav-list" align="center">
    <li class="nav-header"  data-toggle="collapse" data-target="#test">
      <h8>Navegação</h8><span class="service_button fa fa-chevron-down fa-2x"></span>
      <ul class="nav list-group collapse" id="test">
        <li><a href="<%=atendimentos_path%>"> <h7>Atendimentos</h7></a></li>
        <li><a href="<%=places_path%>">Locais de Atendimento</a></li>
        <li><a href="<%=types_path%>">Tipos de Atendimento</a></li>


  </div><!--/.nav-collapse -->
</div>

<script type="text/javascript">
    $('#test').on('shown.bs.collapse'), function() {
        console.log("oi")
        $(".service_button").addClass('fa fa-chevron-up"').removeClass('fa fa-chevron-down"');
    }

</script>